package com.thirtydegreesray.openhub.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RELEASE_COMMIT".
 */
@Entity
public class ReleaseCommit {

    @Id
    @NotNull
    private String key;

    @NotNull
    private String sha;

    @Generated
    public ReleaseCommit() {
    }

    public ReleaseCommit(String key) {
        this.key = key;
    }

    @Generated
    public ReleaseCommit(String key, String sha) {
        this.key = key;
        this.sha = sha;
    }

    @NotNull
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(@NotNull String key) {
        this.key = key;
    }

    @NotNull
    public String getSha() {
        return sha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSha(@NotNull String sha) {
        this.sha = sha;
    }

}
