package com.thirtydegreesray.openhub.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RELEASE_COMMIT".
*/
public class ReleaseCommitDao extends AbstractDao<ReleaseCommit, String> {

    public static final String TABLENAME = "RELEASE_COMMIT";

    /**
     * Properties of entity ReleaseCommit.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Sha = new Property(1, String.class, "sha", false, "SHA");
    }


    public ReleaseCommitDao(DaoConfig config) {
        super(config);
    }
    
    public ReleaseCommitDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RELEASE_COMMIT\" (" + //
                "\"KEY\" TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "\"SHA\" TEXT NOT NULL );"); // 1: sha
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RELEASE_COMMIT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReleaseCommit entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getKey());
        stmt.bindString(2, entity.getSha());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReleaseCommit entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getKey());
        stmt.bindString(2, entity.getSha());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public ReleaseCommit readEntity(Cursor cursor, int offset) {
        ReleaseCommit entity = new ReleaseCommit( //
            cursor.getString(offset + 0), // key
            cursor.getString(offset + 1) // sha
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReleaseCommit entity, int offset) {
        entity.setKey(cursor.getString(offset + 0));
        entity.setSha(cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ReleaseCommit entity, long rowId) {
        return entity.getKey();
    }
    
    @Override
    public String getKey(ReleaseCommit entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReleaseCommit entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
